create table LAPTOPS (
    id INT  NOT NULL,
    serial VARCHAR(50)
);
ALTER TABLE LAPTOPS ADD CONSTRAINT PK_LAPTOPS PRIMARY KEY (id);

create table EMPLOYEES (
    id INT NOT NULL,
    name VARCHAR(50),
    laptop_id INT
);
ALTER TABLE EMPLOYEES ADD CONSTRAINT PK_EMPLOYEES PRIMARY KEY (id);
ALTER TABLE EMPLOYEES ADD CONSTRAINT FK_EMPLOYEES_LAPTOPS FOREIGN KEY (laptop_id) REFERENCES LAPTOPS(id);

create table ROLES (
    id INT  NOT NULL,
    role VARCHAR(50)
);
ALTER TABLE ROLES ADD CONSTRAINT PK_ROLES PRIMARY KEY (id);

create table EMPLOYEES_ROLES (
    employee_id INT NOT NULL,
    role_id INT NOT NULL
);